#!/usr/bin/env python3
# Packs the frens' art (script/art/data: made by the art kit's export_v2.py) into data contracts IMD's launch can deploy
# with no arguments, and the index the renderer reads them by:
#   src/FrenArtChunks.sol  FrenArtChunk1..N: each one's code is a STOP byte, then up to 24,575 bytes of art
#   src/FrenArtIndex.sol   where each layer and the palette sit (chunk, offset, length), the colour tables, the face
#                          table, the shadow, and each chunk's exact code size
#   python3 script/art/chunks.py
import json, os

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.join(here, "..", "..")
data = os.path.join(here, "data")
m = json.load(open(os.path.join(data, "manifest.json")))
names = m["layers"]
blobs = [open(os.path.join(data, "layers", n + ".bin"), "rb").read() for n in names]
palette = open(os.path.join(data, "palette.bin"), "rb").read()
tables = open(os.path.join(data, "tables.bin"), "rb").read()
face = open(os.path.join(data, "facetable.bin"), "rb").read()
shadow = int(m["shadow"])
assert len(palette) == 1024 and len(tables) == 29 and len(face) == 39, (len(palette), len(tables), len(face))

CAP = 24576 - 1  # EIP-170, less the STOP byte
entries = blobs + [palette]  # entry i < len(names): layer i; the last: the palette
chunks, index, cur = [], [], bytearray()
for b in entries:
    assert len(b) <= CAP
    if len(cur) + len(b) > CAP:
        chunks.append(bytes(cur))
        cur = bytearray()
    index.append((len(chunks), len(cur), len(b)))
    cur += b
chunks.append(bytes(cur))
assert len(chunks) == 7, f"the renderer takes 7 chunks, the art needs {len(chunks)}"
for c, off, n in index:
    assert off < 1 << 16 and n < 1 << 16

hexlines = lambda b, ind: "\n".join(f'{ind}hex"{b[i:i + 64].hex()}"' for i in range(0, len(b), 64))

out = ["// SPDX-License-Identifier: MIT", "pragma solidity ^0.8.26;", "",
       "// Generated by script/art/chunks.py from script/art/data: never edit by hand.", ""]
for k, c in enumerate(chunks, 1):
    code = b"\x00" + c
    out += [f"/// @notice The frens' art, part {k} of {len(chunks)}: this contract's code is a STOP byte, then {len(c)} bytes of art",
            f"///         (FrenArtIndex says what is where). Calling it does nothing.",
            f"contract FrenArtChunk{k} {{",
            "    constructor() {",
            "        bytes memory code =",
            hexlines(code, "            ") + ";",
            '        assembly ("memory-safe") {',
            "            return(add(code, 32), mload(code))",
            "        }",
            "    }",
            "}", ""]
open(os.path.join(root, "src", "FrenArtChunks.sol"), "w").write("\n".join(out))

idx = b"".join(bytes([c]) + off.to_bytes(2, "big") + n.to_bytes(2, "big") for c, off, n in index)
sizes = b"".join((len(c) + 1).to_bytes(2, "big") for c in chunks)
from Crypto.Hash import keccak as _k  # pycryptodome
def keccak(b):
    h = _k.new(digest_bits=256); h.update(b); return h.digest()
hashes = b"".join(keccak(b"\x00" + c) for c in chunks)
lib = f'''// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

// Generated by script/art/chunks.py from script/art/data: never edit by hand.

/// @notice Where the frens' art sits in the FrenArtChunk contracts. INDEX: 5 bytes per entry (chunk 0-{len(chunks) - 1}, offset
///         and length in the chunk's art, after its STOP byte, big-endian): the {len(names)} layers in order, then the palette.
library FrenArtIndex {{
    uint256 internal constant CHUNKS = {len(chunks)};
    uint256 internal constant LAYERS = {len(names)};
    uint256 internal constant FACE_LAYERS = {m["faceLayers"]};
    uint8 internal constant SHADOW = {shadow};
    bytes internal constant INDEX =
{hexlines(idx, "        ")};
    /// @dev each chunk's code size, 2 bytes big-endian: the renderer checks the chunks it's given
    bytes internal constant CHUNK_SIZES = hex"{sizes.hex()}";
    /// @dev each chunk's code hash (keccak256 of its code): the renderer takes only these chunks
    bytes internal constant CHUNK_HASHES =
{hexlines(hashes, "        ")};
    /// @dev lens 4x2, coat 3x5, shirt 6: palette indices
    bytes internal constant TABLES = hex"{tables.hex()}";
    /// @dev the layer of character c's face f at c * 13 + f
    bytes internal constant FACE_TABLE = hex"{face.hex()}";
}}
'''
open(os.path.join(root, "src", "FrenArtIndex.sol"), "w").write(lib)
print("chunks", [len(c) for c in chunks], "entries", len(index), "index bytes", len(idx))
